POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content":"user if of the note creator is at the start sent along the request",
    "important": true,
    "userId": "6753d250997c0d2d8f51d56a"
}